server:
  port: 8080

spring:

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest
  data:
    mongodb:
      database: root
      uri: mongodb://root:123456@localhost:27017

logging:
  level:
    org:
      apache:
        kafka: OFF